app: techtrends

namespace: 
  name: sandbox
name: techtrends

service:
  name: techtrends
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

container:
  name: techtrends
  port: 3111
  image: varsanyim/techtrends:latest

image:
  repository: varsanyim/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

probes:
  liveness:
    path: /healthz
    port: 3111
  readiness:
    path: /healthz
    port: 3111
