namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

container:
  name: techtrends
  port: 3111

probe:
  liveness:
    httpGet:
      path: /healthz
      port: 3111
  readiness:
    httpGet:
      path: /healthz
      port: 3111